bookshelf/Models/ErrorViewModel.cs
using System;

namespace bookshelf.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

bookshelf/Models/Member.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace bookshelf.Models
{
    public partial class Member
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string RentBook { get; set; }
    }
}

bookshelf/Models/UyelerContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace bookshelf.Models
{
    public partial class UyelerContext : DbContext
    {
        public UyelerContext()
        {
        }

        public UyelerContext(DbContextOptions<UyelerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Member> Members { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=.\\;Database=Uyeler;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<Member>(entity =>
            {
                entity.ToTable("Member");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.Name).HasMaxLength(20);

                entity.Property(e => e.Phone).HasMaxLength(13);

                entity.Property(e => e.RentBook).HasMaxLength(40);

                entity.Property(e => e.Surname).HasMaxLength(20);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

bookshelf/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookshelf.Controllers
{
    public class BooksController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult AddBook()
        {
            return View();
        }

        public ActionResult EditBook()
        {
            return View();
        }

    }
}

bookshelf/Controllers/HomeController.cs
using bookshelf.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace bookshelf.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public ActionResult Book()
        {
            return View();
        }

        public ActionResult AnaSayfa()
        {
            return View();
        }
    }
}

bookshelf/Controllers/MemberController.cs
using bookshelf.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookshelf.Controllers
{
    public class MemberController : Controller
    {
        UyelerContext uyelerContext = new UyelerContext();
        public IActionResult Index()
        {
            var model = uyelerContext.Members.ToList();

            return View(model);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Member member)
        {
            var model = uyelerContext.Members.Add(member);
            uyelerContext.SaveChanges();
            return RedirectToAction("Index","Member");
        }

        public IActionResult Delete(int id)
        {
            var silinecek = uyelerContext.Members.Find(id);
            var model = uyelerContext.Members.Remove(silinecek);
            uyelerContext.SaveChanges();
            return RedirectToAction("Index", "Member");
        }

    }
}

bookshelf/Controllers/ikinciController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookshelf.Controllers
{
    public class ikinciController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Conctact()
        {
            return View();
        }
    }
}

bookshelf/Views/Books/AddBook.cshtml
@{
    ViewData["Title"] = "AddBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Kitap Ekle</h1>

bookshelf/Views/Books/EditBook.cshtml
@model bookshelf.Startup

@{
    ViewData["Title"] = "EditBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Kitap Düzenle</h1>

bookshelf/Views/Home/AnaSayfa.cshtml
@{
    ViewData["Title"] = "AnaSayfa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AnaSayfa</h1>

<h4>Şu an anasayfadasınız</h4>

bookshelf/Views/Home/Book.cshtml
@{
    ViewData["Title"] = "Book";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Book</h1>
<h2>Tüm Kitaplar</h2>

bookshelf/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hoşgeldiniz</h1>
</div>
<h1>Burası index</h1>

bookshelf/Views/Member/Add.cshtml
@model bookshelf.Models.Member

@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" method="post" asp-controller="Member">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RentBook" class="control-label"></label>
                <input asp-for="RentBook" class="form-control" />
                <span asp-validation-for="RentBook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

bookshelf/Views/Member/Index.cshtml
@model IEnumerable<bookshelf.Models.Member>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Add">Ekle</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentBook)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RentBook)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Düzenle</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Sil</a>
            </td>
        </tr>
}   
    </tbody>
</table>

bookshelf/Views/Shared/_Footer.cshtml
<footer style="background-color: #ff6e6894;" class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - bookshelf - Burak Akdeniz Tüm hakları saklıdır. <a style="float:right" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

bookshelf/Views/Shared/_Header.cshtml
<header>
    <nav style="background-color:#e3f2fd" class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Kitaplık</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item border-left">
                        <a class="nav-link text-dark font-weight-bold m-2" asp-area="" asp-controller="Home" asp-action="AnaSayfa">Ana Sayfa</a>
                    </li>
                    <li class="nav-item border-left">
                        <a class="nav-link text-dark font-weight-bold m-2" asp-area="" asp-controller="Member" asp-action="Index">Üyeler</a>
                    </li>
                    <li class="nav-item border-left">
                        <a class="nav-link text-dark font-weight-bold m-2" asp-area="" asp-controller="ikinci" asp-action="Conctact">İletişim</a>
                    </li>
                    <li class="nav-item border-left">
                        <a class="nav-link text-dark font-weight-bold m-2" asp-area="" asp-controller="Home" asp-action="Book">Kitaplar</a>
                    </li>
                    <li class="nav-item border-left">
                        <a class="nav-link text-dark font-weight-bold m-2" asp-area="" asp-controller="Books" asp-action="AddBook">Kitap Ekle</a>
                    </li>
                    <li class="nav-item border-left">
                        <a class="nav-link text-dark font-weight-bold m-2" asp-area="" asp-controller="Books" asp-action="EditBook">Kitap Düzenle</a>
                    </li>
                </ul>

            </div>
            <form style="float:right; margin-right:5px; width: 30em;" class="d-flex">
                <input class="form-control mr-2 " type="search" placeholder="Search" aria-label="Ara">
                <button class="btn btn-outline-success ml-4" type="submit">Ara</button>
            </form>
        </div>
    </nav>
</header>

bookshelf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bookshelf</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <partial name="_Header.cshtml" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
        <partial name="_Footer.cshtml" />
</body>


</html>

bookshelf/Views/ikinci/Conctact.cshtml
@{
    ViewData["Title"] = "Conctact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <h1>Conctact</h1>
    <h2> Bizimle İletişime Geçebilirsiniz</h2>
    <p> İletişim için adresler: XXXXXXXXXXXXX</p>
</body>